line-length = 100
target-version = "py312"

[lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]

[lint.per-file-ignores]
"packages/project-cnn/**" = ["F401", "F821", "F841", "E402", "F403", "F405", "I001", "E712"]
"packages/pure-alexnet/**" = ["F401", "F821", "F841", "E402", "F403", "F405", "I001"]
"packages/dfp-formula-project/**" = ["E402", "F403", "F405", "I001", "F401", "F841", "E741", "E703"]
